#!/usr/bin/ansible-playbook
---
- hosts: localhost

  tasks:
  - name: create docker image
    command: docker build -t regapp:latest -f ../Dockerfile

  - name: create tag to push image onto dockerhub
    command: docker tag regapp:latest ajayyeruva18/regapp:latest

  - name: push docker image
    command: docker push ajayyeruva18/regapp:latest
