#!/usr/bin/ansible-playbook
---
- hosts: localhost
  become: true

  tasks:
  - name: create docker image
    command: sudo docker build -t regapp:latest .

  - name: create tag to push image onto dockerhub
    command: sudo docker tag regapp:latest ajayyeruva18/regapp:latest

  - name: push docker image
    command: sudo docker push ajayyeruva18/regapp:latest
