#!/usr/bin/ansible-playbook
---
- hosts: localhost
  become: false

  tasks:
  - name: create docker image
    command: docker build -t regapp:latest .

  - name: create tag to push image onto dockerhub
    command: docker tag regapp:latest sai1107/regapp:latest

  - name: push docker image
    command: docker push sai1107/regapp:latest
