apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: efp-deployment
spec:
  selector:
    matchLabels:
      app: efp-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: efp-devops-project
    spec:
      containers:
      - name: efp-devops-project
        image: sai1107/regapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
