---
- name: Create pods using deployment 
  hosts: localhost
  become: false
  # user: ubuntu
 
  tasks: 
  - name: create a deployment
    command: sudo kubectl apply -f efp-deploy.yml
 
  - name: update deployment with new pods if image updated in docker hub
    command: sudo kubectl rollout restart deployment.v1.apps/efp-deployment
