---
- name: Create pods using deployment 
  hosts: localhost
  tasks: 
  - name: create a deployment
    command: source ~/.bashrc && kubectl apply -f efp-deploy.yml

  - name: update deployment with new pods if image updated in docker hub
    command: source ~/.bashrc && kubectl rollout restart deployment.v1.apps/efp-deployment
